name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: |
          version=$(cat schulmanager/manifest.json | jq -r '.version')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Update version in manifest
        run: |
          sed -i 's/"version": ".*"/"version": "'${{ github.event.release.tag_name }}'"/' schulmanager/manifest.json

      - name: Zip integration
        run: |
          cd schulmanager
          zip -r ../schulmanager-${{ github.event.release.tag_name }}.zip . -x "*.pyc" "__pycache__/*" "debug/*"

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: schulmanager-${{ github.event.release.tag_name }}.zip
          asset_name: schulmanager-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip